version: "3"
services:
  airflow-webserver:
    image: apache/airflow
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_HOME=~/airflow
